import { Movie, Category } from '../types';

export const defaultCategories: Category[] = [
  { id: '1', name: 'Action', icon: '⚔️' },
  { id: '2', name: 'Comedy', icon: '😂' },
  { id: '3', name: 'Drama', icon: '🎭' },
  { id: '4', name: 'Sci-Fi', icon: '🚀' },
  { id: '5', name: 'Horror', icon: '👻' },
  { id: '6', name: 'Thriller', icon: '🔪' },
  { id: '7', name: 'Romance', icon: '❤️' },
  { id: '8', name: 'Animation', icon: '🎨' },
  { id: '9', name: 'Documentary', icon: '📷' },
  { id: '10', name: 'Fantasy', icon: '🧙' },
  { id: '11', name: 'Mystery', icon: '🔍' },
  { id: '12', name: 'Adventure', icon: '🗺️' },
];

export const defaultMovies: Movie[] = [
  {
    id: '1',
    title: 'The Last Horizon',
    description: 'In a world ravaged by climate catastrophe, a lone pilot embarks on a desperate mission to find the last habitable zone on Earth. Facing treacherous storms and hostile survivors, she must navigate through the ruins of civilization to save what remains of humanity.',
    rating: 8.7,
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    releaseYear: 2024,
    duration: '2h 23m',
    poster: 'https://picsum.photos/seed/movie1/400/600',
    backdrop: 'https://picsum.photos/seed/movie1bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    featured: true,
    trending: true,
    latest: true,
    topRated: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Midnight Echo',
    description: 'A brilliant detective with synesthesia uncovers a serial killer who leaves musical clues at crime scenes. As the investigation deepens, she realizes the killer is composing a symphony of murder with her as the final note.',
    rating: 8.2,
    genre: ['Thriller', 'Mystery', 'Drama'],
    releaseYear: 2024,
    duration: '2h 05m',
    poster: 'https://picsum.photos/seed/movie2/400/600',
    backdrop: 'https://picsum.photos/seed/movie2bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    featured: false,
    trending: true,
    latest: true,
    topRated: true,
    createdAt: '2024-02-10',
  },
  {
    id: '3',
    title: 'Whispers in the Dark',
    description: 'After moving into an old Victorian mansion, a family discovers that the house harbors dark secrets from the 19th century. When the youngest child begins communicating with unseen entities, the parents must confront an ancient evil that feeds on fear.',
    rating: 7.8,
    genre: ['Horror', 'Mystery'],
    releaseYear: 2023,
    duration: '1h 52m',
    poster: 'https://picsum.photos/seed/movie3/400/600',
    backdrop: 'https://picsum.photos/seed/movie3bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    featured: false,
    trending: true,
    latest: false,
    topRated: false,
    createdAt: '2023-10-31',
  },
  {
    id: '4',
    title: 'Love in Paris',
    description: 'Two strangers from different worlds meet accidentally in a cozy Parisian café. As they explore the City of Lights together over one magical week, they discover that love can bloom in the most unexpected places and the most unexpected times.',
    rating: 7.5,
    genre: ['Romance', 'Drama', 'Comedy'],
    releaseYear: 2024,
    duration: '1h 58m',
    poster: 'https://picsum.photos/seed/movie4/400/600',
    backdrop: 'https://picsum.photos/seed/movie4bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    featured: false,
    trending: false,
    latest: true,
    topRated: false,
    createdAt: '2024-02-14',
  },
  {
    id: '5',
    title: 'Starbound Odyssey',
    description: 'When Earth receives a mysterious signal from deep space, a diverse crew of astronauts is assembled for humanity\'s first interstellar journey. What they find at the source challenges everything they know about the universe and themselves.',
    rating: 9.1,
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    releaseYear: 2024,
    duration: '2h 45m',
    poster: 'https://picsum.photos/seed/movie5/400/600',
    backdrop: 'https://picsum.photos/seed/movie5bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    featured: true,
    trending: true,
    latest: true,
    topRated: true,
    createdAt: '2024-03-01',
  },
  {
    id: '6',
    title: 'The Comedy Club',
    description: 'Three down-on-their-luck comedians decide to open their own comedy club in a dying mall. Through hilarious mishaps, terrible open mic nights, and unexpected viral fame, they learn that the best punchlines come from real life.',
    rating: 7.3,
    genre: ['Comedy'],
    releaseYear: 2023,
    duration: '1h 42m',
    poster: 'https://picsum.photos/seed/movie6/400/600',
    backdrop: 'https://picsum.photos/seed/movie6bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    featured: false,
    trending: false,
    latest: false,
    topRated: false,
    createdAt: '2023-07-20',
  },
  {
    id: '7',
    title: 'Dragon\'s Keep',
    description: 'In a realm where dragons and humans once lived in harmony, a young sorceress must restore the ancient bond between species before a power-hungry king unleashes a war that could destroy both civilizations forever.',
    rating: 8.5,
    genre: ['Fantasy', 'Adventure', 'Action'],
    releaseYear: 2024,
    duration: '2h 30m',
    poster: 'https://picsum.photos/seed/movie7/400/600',
    backdrop: 'https://picsum.photos/seed/movie7bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    featured: false,
    trending: true,
    latest: true,
    topRated: true,
    createdAt: '2024-01-05',
  },
  {
    id: '8',
    title: 'The Deep Blue',
    description: 'A team of marine biologists discovers a vast underwater civilization hidden beneath the Marianas Trench. As they attempt to make contact, they uncover secrets that could reshape our understanding of life on Earth and its origins.',
    rating: 8.0,
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    releaseYear: 2023,
    duration: '2h 12m',
    poster: 'https://picsum.photos/seed/movie8/400/600',
    backdrop: 'https://picsum.photos/seed/movie8bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    featured: false,
    trending: false,
    latest: false,
    topRated: true,
    createdAt: '2023-06-15',
  },
  {
    id: '9',
    title: 'Pixel Warriors',
    description: 'When a glitch in the world\'s most popular video game starts affecting reality, a group of gamers must enter the digital realm to fix the code before the virtual and real worlds collide in catastrophic fashion.',
    rating: 7.9,
    genre: ['Animation', 'Action', 'Comedy'],
    releaseYear: 2024,
    duration: '1h 48m',
    poster: 'https://picsum.photos/seed/movie9/400/600',
    backdrop: 'https://picsum.photos/seed/movie9bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    featured: false,
    trending: true,
    latest: true,
    topRated: false,
    createdAt: '2024-03-15',
  },
  {
    id: '10',
    title: 'The Untold Story',
    description: 'An award-winning documentary that follows the lives of five refugees as they navigate the complex and often heartbreaking journey to find a new home. A powerful testament to human resilience and the search for belonging.',
    rating: 8.8,
    genre: ['Documentary', 'Drama'],
    releaseYear: 2023,
    duration: '2h 05m',
    poster: 'https://picsum.photos/seed/movie10/400/600',
    backdrop: 'https://picsum.photos/seed/movie10bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    featured: false,
    trending: false,
    latest: false,
    topRated: true,
    createdAt: '2023-09-10',
  },
  {
    id: '11',
    title: 'Shadow Protocol',
    description: 'A retired CIA operative is pulled back into the world of espionage when a mole within the agency threatens to expose undercover agents worldwide. Racing against time, she must navigate a web of deceit to uncover the traitor.',
    rating: 8.3,
    genre: ['Action', 'Thriller'],
    releaseYear: 2024,
    duration: '2h 18m',
    poster: 'https://picsum.photos/seed/movie11/400/600',
    backdrop: 'https://picsum.photos/seed/movie11bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    featured: false,
    trending: true,
    latest: true,
    topRated: true,
    createdAt: '2024-02-28',
  },
  {
    id: '12',
    title: 'The Garden of Time',
    description: 'A botanist discovers a mystical garden where time flows differently. Each plant controls a different aspect of time - past, present, and future. When the garden begins to die, she must find the cure before time itself unravels.',
    rating: 8.1,
    genre: ['Fantasy', 'Drama', 'Mystery'],
    releaseYear: 2023,
    duration: '2h 08m',
    poster: 'https://picsum.photos/seed/movie12/400/600',
    backdrop: 'https://picsum.photos/seed/movie12bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    featured: false,
    trending: false,
    latest: false,
    topRated: false,
    createdAt: '2023-11-22',
  },
  {
    id: '13',
    title: 'Rhythm & Soul',
    description: 'A street dancer from Brooklyn and a classically trained pianist from Vienna are forced to collaborate on a groundbreaking performance. Their clash of styles creates something the world has never seen before.',
    rating: 7.6,
    genre: ['Drama', 'Romance'],
    releaseYear: 2024,
    duration: '1h 55m',
    poster: 'https://picsum.photos/seed/movie13/400/600',
    backdrop: 'https://picsum.photos/seed/movie13bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    featured: false,
    trending: false,
    latest: true,
    topRated: false,
    createdAt: '2024-01-20',
  },
  {
    id: '14',
    title: 'Frozen Fear',
    description: 'Stranded in an Arctic research station during a blizzard, a team of scientists discovers that the ice they\'re studying contains an ancient organism that defrosts with terrifying consequences. Survival becomes the only experiment that matters.',
    rating: 7.4,
    genre: ['Horror', 'Sci-Fi', 'Thriller'],
    releaseYear: 2023,
    duration: '1h 50m',
    poster: 'https://picsum.photos/seed/movie14/400/600',
    backdrop: 'https://picsum.photos/seed/movie14bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    featured: false,
    trending: true,
    latest: false,
    topRated: false,
    createdAt: '2023-12-01',
  },
  {
    id: '15',
    title: 'The Art of War',
    description: 'Set during the Warring States period in ancient China, a brilliant strategist must unite warring kingdoms through diplomacy, deception, and an understanding of human nature that transcends the battlefield.',
    rating: 8.6,
    genre: ['Action', 'Drama', 'Adventure'],
    releaseYear: 2024,
    duration: '2h 35m',
    poster: 'https://picsum.photos/seed/movie15/400/600',
    backdrop: 'https://picsum.photos/seed/movie15bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    featured: true,
    trending: true,
    latest: true,
    topRated: true,
    createdAt: '2024-03-10',
  },
  {
    id: '16',
    title: 'Neon Nights',
    description: 'In a cyberpunk metropolis, a hacktivist fights against a corporation that controls the city\'s water supply. With the help of an AI companion and a ragtag resistance, she must expose the truth before the city runs dry.',
    rating: 8.0,
    genre: ['Sci-Fi', 'Action', 'Thriller'],
    releaseYear: 2024,
    duration: '2h 15m',
    poster: 'https://picsum.photos/seed/movie16/400/600',
    backdrop: 'https://picsum.photos/seed/movie16bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    featured: false,
    trending: true,
    latest: true,
    topRated: false,
    createdAt: '2024-02-05',
  },
  {
    id: '17',
    title: 'The Last Laugh',
    description: 'A veteran comedian diagnosed with a terminal illness decides to go on one final comedy tour across America. Along the way, he rediscovers the healing power of laughter and reconnects with the family he neglected.',
    rating: 8.4,
    genre: ['Comedy', 'Drama'],
    releaseYear: 2023,
    duration: '1h 52m',
    poster: 'https://picsum.photos/seed/movie17/400/600',
    backdrop: 'https://picsum.photos/seed/movie17bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    featured: false,
    trending: false,
    latest: false,
    topRated: true,
    createdAt: '2023-08-14',
  },
  {
    id: '18',
    title: 'Spirit Walker',
    description: 'A young Native American woman discovers she can communicate with ancestral spirits. When a corporation threatens to destroy sacred land, she must use her gift to protect her heritage while bridging the gap between the modern and spirit worlds.',
    rating: 7.7,
    genre: ['Fantasy', 'Drama', 'Mystery'],
    releaseYear: 2024,
    duration: '2h 02m',
    poster: 'https://picsum.photos/seed/movie18/400/600',
    backdrop: 'https://picsum.photos/seed/movie18bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    featured: false,
    trending: false,
    latest: true,
    topRated: false,
    createdAt: '2024-01-30',
  },
  {
    id: '19',
    title: 'Breaking Point',
    description: 'A professional boxer at the peak of her career faces her toughest opponent yet: herself. After a devastating loss, she must rebuild her life, confront her demons, and find the strength to step back into the ring one last time.',
    rating: 8.2,
    genre: ['Drama', 'Action'],
    releaseYear: 2023,
    duration: '2h 10m',
    poster: 'https://picsum.photos/seed/movie19/400/600',
    backdrop: 'https://picsum.photos/seed/movie19bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    featured: false,
    trending: true,
    latest: false,
    topRated: true,
    createdAt: '2023-05-20',
  },
  {
    id: '20',
    title: 'Wonderland Express',
    description: 'A magical train that travels through storybook worlds picks up a lonely child who has stopped believing in imagination. Together with a cast of whimsical characters, the child embarks on an enchanting journey to rediscover the magic within.',
    rating: 8.9,
    genre: ['Animation', 'Fantasy', 'Adventure'],
    releaseYear: 2024,
    duration: '1h 45m',
    poster: 'https://picsum.photos/seed/movie20/400/600',
    backdrop: 'https://picsum.photos/seed/movie20bg/1920/1080',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    featured: false,
    trending: true,
    latest: true,
    topRated: true,
    createdAt: '2024-03-20',
  },
];
